version: "3.9"
services:
  api:
      build: .
      container_name: gapstack_api
      volumes:
        - .:/app
      depends_on:
        - postgres
      networks:
        - gapstack-net
      ports:
        - "8080:8080"
  postgres:
    image: postgres:latest
    container_name: gapstack-postgres
    hostname: gapstack-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - gapstack-net
    env_file:
      - ./app.env

volumes:
  db:
networks:
  gapstack-net:
    driver: bridge