CREATE EXTENSION IF NOT EXISTS  "uuid-ossp";

CREATE TABLE IF NOT EXISTS transactions (
  id UUID NOT NULL DEFAULT (uuid_generate_v4()) PRIMARY KEY,
  amount REAL NOT NULL,
  currency TEXT NOT NULL,
  sender TEXT NOT NULL,
  receiver TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
